{% set version = "6.7.1" %}
{% set pyqt_webengine_version = "6.7.0" %}
{% set pyqt_sip_version = "13.9.1" %}
{% set pyqt_sip_pkg_name = "PyQt" + version[0] + "-sip" %}

package:
  name: pyqt-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/P/PyQt{{ version[0] }}/PyQt{{ version[0] }}-{{ version }}.tar.gz
    sha256: 3672a82ccd3a62e99ab200a13903421e2928e399fda25ced98d140313ad59cb9
    folder: pyqt
  - url: https://pypi.org/packages/source/P/{{ pyqt_sip_pkg_name }}/{{ pyqt_sip_pkg_name.replace("-", "_") | lower }}-{{ pyqt_sip_version }}.tar.gz
    sha256: 15be741d1ae8c82bb7afe9a61f3cf8c50457f7d61229a1c39c24cd6e8f4d86dc
    folder: pyqt_sip
  - url: https://pypi.org/packages/source/P/PyQt{{ version[0] }}-WebEngine/PyQt{{ version[0] }}_WebEngine-{{ pyqt_webengine_version }}.tar.gz
    sha256: 68edc7adb6d9e275f5de956881e79cca0d71fad439abeaa10d823bff5ac55001
    folder: pyqt_webengine

build:
  number: 2
  skip: true  # [py<38]
  skip: true  # [osx and x86_64]

outputs:
  - name: {{ pyqt_sip_pkg_name | lower }}
    version: {{ pyqt_sip_version }}
    script: build-pyqt-sip.sh  # [not win]
    script: bld-pyqt-sip.bat  # [win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
      host:
        - python
        - setuptools
        - wheel
        - pip
      run:
        - python
        - sip
        - packaging
        - toml
    test:
      imports:
        - PyQt{{ version[0] }}.sip
      requires:
        - pip
      commands:
        - pip check

  - name: pyqt
    version: {{ version }}
    script: build-pyqt.sh  # [not win]
    script: bld-pyqt.bat  # [win]
    build:
      entry_points:
        - pyuic{{ version[0] }} = PyQt{{ version[0] }}.uic.pyuic:main
      run_exports:
        - {{ pin_subpackage('pyqt', max_pin='x.x') }}
      missing_dso_whitelist:
        - $RPATH/libm.so.6
        - $RPATH/libpthread.so.0
        - $RPATH/libc.so.6
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - jom                                # [win]
        - make                               # [not win]
        - pkg-config
      host:
        - python
        - pyqt-builder >=1.15,<2
        - sip >=6.8.6,<7
        - qtbase-devel {{ qt }}
        # OpenGL and X11 dependencies
        - libgl-devel {{ libgl }}         # [linux]
        - libegl-devel {{ libegl}}        # [linux]
        - libopengl-devel {{ libopengl }} # [linux]
        - libdrm {{ libdrm }}             # [linux]
      run:
        - python
        - {{ pin_subpackage(pyqt_sip_pkg_name | lower, exact=True) }}
    test:
      files:
        - pyqt_test.py
      imports:
        - PyQt6
        - PyQt6.sip
        - PyQt6.QtCore
        - PyQt6.QtGui
        - PyQt6.QtHelp
        # - PyQt6.QtMultimedia # Made add-on in Qt6?
        # - PyQt6.QtMultimediaWidgets # Made add-on in Qt6?
        - PyQt6.QtNetwork
        - PyQt6.QtOpenGL
        - PyQt6.QtOpenGLWidgets # New in Qt6?
        - PyQt6.QtPrintSupport
        - PyQt6.QtQml
        - PyQt6.QtQuick
        - PyQt6.QtQuickWidgets # New in Qt6?
        - PyQt6.QtSvg
        - PyQt6.QtSvgWidgets # New in Qt6?
        - PyQt6.QtTest
        - PyQt6.QtWebChannel
        - PyQt6.QtWebSockets
        - PyQt6.QtWidgets
        - PyQt6.QtXml
      requires:
        - pip
        # X11 dependencies
        - libgl  # [linux]
        - libegl  # [linux]
        - libglx  # [linux]
        - mesalib  # [linux]
        - libxcb  # [linux]
        - xorg-libx11  # [linux]
        - xorg-libxext  # [linux]
      commands:
        - pip check

  - name: pyqtwebengine
    version: {{ pyqt_webengine_version }}
    script: build-pyqtwebengine.sh  # [not win]
    script: bld-pyqtwebengine.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('pyqtwebengine', max_pin='x.x') }}
      missing_dso_whitelist:
        - $RPATH/libm.so.6
        - $RPATH/libpthread.so.0
        - $RPATH/libc.so.6
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - jom  # [win]
        - make  # [not win]
        - pkg-config
      host:
        - python
        - pyqt-builder >=1.15,<2
        - sip >=6.8.6,<7
        - {{ pin_subpackage('pyqt', exact=True) }}
        - qtbase-devel {{ qt }}
        - qtdeclarative {{ qt }}
        - qtwebchannel {{ qt }}
        - qtwebengine {{ qt }}
        # OpenGL and X11 dependencies
        - libgl-devel {{ libgl }}               # [linux]
        - libegl-devel {{ libegl}}              # [linux]
        - libopengl-devel {{ libopengl }} # [linux]
      run:
        - python
        - {{ pin_subpackage('pyqt', max_pin='x.x') }}
    test:
      imports:
        - PyQt{{ version[0] }}
      requires:
        - pip
        # X11 dependencies
        - libgl  # [linux]
        - libegl  # [linux]
        - libglx  # [linux]
        - mesalib  # [linux]
        - libxcb  # [linux]
        - xorg-libx11  # [linux]
        - xorg-libxext  # [linux]
      commands:
        - pip check

about:
  home: https://www.riverbankcomputing.com/software/pyqt/
  license: GPL-3.0-only
  license_family: GPL
  license_file: pyqt/LICENSE
  summary: Python bindings for the Qt cross platform application toolkit
  description: |
    PyQt{{ version[0] }} is a comprehensive set of Python bindings for Qt v{{ version[0] }}.
    It is implemented as more than 35 extension modules and enables Python
    to be used as an alternative application development language to C++ on
    all supported platforms including iOS and Android.
  doc_url: https://www.riverbankcomputing.com/static/Docs/PyQt{{ version[0] }}/
  dev_url: https://www.riverbankcomputing.com/mailman/listinfo/pyqt/

extra:
  skip-lints:
    - missing_wheel
    - missing_python_build_tool
    - host_section_needs_exact_pinnings
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - katietz
    - mingwandroid
    - gillins
    - msarahan
    - ocefpaf
    - jschueller
  feedstock-name: pyqt
