{% set version = "6.9.1" %}
{% set pyqt_webengine_version = "6.9.0" %}
{% set pyqt_sip_version = "13.10.2" %}
{% set pyqt_sip_pkg_name = "PyQt" + version[0] + "-sip" %}

# The version of Qt packages being built against must match because sip detects the version for some things in qt-main
# and then assumes that the remaining packages, such as qtwebengine, will also be at that exact same version.
{% set qt_version = "6.9.2" %}

package:
  name: pyqt-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/P/PyQt{{ version[0] }}/pyqt{{ version[0] }}-{{ version }}.tar.gz
    sha256: 50642be03fb40f1c2111a09a1f5a0f79813e039c15e78267e6faaf8a96c1c3a6
    folder: pyqt

  - url: https://pypi.org/packages/source/P/{{ pyqt_sip_pkg_name }}/{{ pyqt_sip_pkg_name.replace("-", "_") | lower }}-{{ pyqt_sip_version }}.tar.gz
    sha256: 464ad156bf526500ce6bd05cac7a82280af6309974d816739b4a9a627156fafe
    folder: pyqt_sip

  - url: https://pypi.org/packages/source/P/PyQt{{ version[0] }}-WebEngine/pyqt{{ version[0] }}_webengine-{{ pyqt_webengine_version }}.tar.gz
    sha256: 6ae537e3bbda06b8e06535e4852297e0bc3b00543c47929541fcc9b11981aa25
    folder: pyqt_webengine

build:
  number: 1
  skip: True  # [py<39]

outputs:
  - name: {{ pyqt_sip_pkg_name | lower }}
    version: {{ pyqt_sip_version }}
    script: build-pyqt-sip.sh  # [not win]
    script: bld-pyqt-sip.bat   # [win]
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
      host:
        - python
        - setuptools >=75.8.1
        - wheel
        - pip
      run:
        - python
    test:
      imports:
        - PyQt6.sip
      requires:
        - pip
      commands:
        - pip check

  - name: pyqt
    version: {{ version }}
    script: build-pyqt.sh  # [not win]
    script: bld-pyqt.bat   # [win]
    build:
      entry_points:
        - pylupdate6 = PyQt6.lupdate.pylupdate:main
        - pyuic6 = PyQt6.uic.pyuic:main
      run_exports:
        - {{ pin_subpackage('pyqt', max_pin='x.x') }}
      missing_dso_whitelist:
        - $RPATH/libm.so.6
        - $RPATH/libpthread.so.0
        - $RPATH/libc.so.6
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - jom                             # [win]
        - make                            # [not win]
        - pkg-config
      host:
        - python
        - pyqt-builder >=1.17,<2
        - sip >=6.12,<7
        - qtbase-devel {{ qt_version }}
        - qtdeclarative {{ qt_version }}
        - qtsvg {{ qt_version }}
        - qttools {{ qt_version }}
        - qtwayland  {{ qt_version }}        # [linux]
        - qtwebchannel {{ qt_version }}
        - qtwebsockets {{ qt_version }}
        # OpenGL and X11 dependencies
        - libgl-devel {{ libgl }}            # [linux]
        - libvulkan-headers {{ libvulkan }}  # [not osx]
        - libvulkan-loader {{ libvulkan }}   # [not osx]
      run:
        - python
        - {{ pin_subpackage(pyqt_sip_pkg_name | lower, exact=True) }}
    test:
      files:
        - pyqt_test.py
      imports:
        - PyQt6
        - PyQt6.QtCore
        - PyQt6.QtDBus
        - PyQt6.QtDesigner
        - PyQt6.QtGui
        - PyQt6.QtHelp
        - PyQt6.QtNetwork
        - PyQt6.QtOpenGL
        - PyQt6.QtOpenGLWidgets
        - PyQt6.QtPrintSupport
        - PyQt6.QtQml
        - PyQt6.QtQuick
        - PyQt6.QtQuickWidgets
        - PyQt6.QtSql
        - PyQt6.QtSvg
        - PyQt6.QtSvgWidgets
        - PyQt6.QtTest
        - PyQt6.QtWebChannel
        - PyQt6.QtWebSockets
        - PyQt6.QtWidgets
        - PyQt6.QtXml
      requires:
        - pip
      commands:
        - pip check

  - name: pyqtwebengine
    version: {{ pyqt_webengine_version }}
    script: build-pyqtwebengine.sh  # [not win]
    script: bld-pyqtwebengine.bat   # [win]
    build:
      run_exports:
        - {{ pin_subpackage('pyqtwebengine', max_pin='x.x') }}
      missing_dso_whitelist:
        - $RPATH/libm.so.6
        - $RPATH/libpthread.so.0
        - $RPATH/libc.so.6
    requirements:
      build:
        - {{ stdlib('c') }}
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - jom   # [win]
        - make  # [not win]
        - pkg-config
      host:
        - python
        - pyqt-builder >=1.17,<2
        - sip >=6.9,<7
        - {{ pin_subpackage('pyqt', exact=True) }}
        - qtbase-devel {{ qt_version }}
        - qtdeclarative {{ qt_version }}
        - qtwebchannel {{ qt_version }}
        - qtwebengine {{ qt_version }}
        # OpenGL and X11 dependencies
        - libgl-devel {{ libgl }}            # [linux]
        - libvulkan-headers {{ libvulkan }}  # [not osx]
        - libvulkan-loader {{ libvulkan }}   # [not osx]
      run:
        - python
        - {{ pin_subpackage('pyqt', max_pin='x.x') }}
    test:
      imports:
        - PyQt6.QtWebEngineCore
        - PyQt6.QtWebEngineQuick
        - PyQt6.QtWebEngineWidgets
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://www.riverbankcomputing.com/software/pyqt/
  license: GPL-3.0-only
  license_family: GPL
  license_file: pyqt/LICENSE
  summary: Python bindings for the Qt cross platform application toolkit
  description: |
    PyQt{{ version[0] }} is a comprehensive set of Python bindings for Qt v{{ version[0] }}.
    It is implemented as more than 35 extension modules and enables Python
    to be used as an alternative application development language to C++ on
    all supported platforms including iOS and Android.
  doc_url: https://www.riverbankcomputing.com/static/Docs/PyQt{{ version[0] }}/
  dev_url: https://www.riverbankcomputing.com/mailman/listinfo/pyqt/

extra:
  skip-lints:
    - missing_python_build_tool
    - host_section_needs_exact_pinnings
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - katietz
    - mingwandroid
    - gillins
    - msarahan
    - ocefpaf
    - jschueller
  feedstock-name: pyqt
