{% set version = "5.15.11" %}
{% set sip_version = "6.12.0" %}
{% set pyqt5_sip_version = "12.17.0" %}
{% set webengine_version = "5.15.7" %}
{% set charts_version = "5.15.7" %}
# on our builders there is no X11 installed and therefore import
# test will fail
{% if target_platform != "linux-aarch64" and target_platform != "linux-64"%}
{% set enable_testingui = true %}
{% else %}
{% set enable_testingui = false %}
{% endif %}

package:
  name: pyqt-split
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/P/PyQt{{ version[0] }}/PyQt{{ version[0] }}-{{ version }}.tar.gz
    sha256: fda45743ebb4a27b4b1a51c6d8ef455c4c1b5d610c90d2934c7802b5c1557c52
    folder: pyqt

  - url: https://pypi.org/packages/source/P/PyQt5-sip/pyqt5_sip-{{ pyqt5_sip_version }}.tar.gz
    sha256: 682dadcdbd2239af9fdc0c0628e2776b820e128bec88b49b8d692fe682f90b4f
    folder: pyqt_sip

  - url: https://pypi.org/packages/source/P/PyQtWebEngine/PyQtWebEngine-{{ webengine_version }}.tar.gz
    sha256: f121ac6e4a2f96ac289619bcfc37f64e68362f24a346553f5d6c42efa4228a4d
    folder: pyqt_webengine

  - url: https://pypi.org/packages/source/P/PyQtChart/PyQtChart-{{ charts_version }}.tar.gz
    sha256: bc9f1d26c725e820b0fff8db6e906e8b286128a14b3a98c59a0cd0c3d9924095
    folder: pyqt_charts

build:
  number: 0

outputs:
  - name: pyqt5-sip
    version: {{ pyqt5_sip_version }}
    script: build-pyqt-sip.sh  # [not win]
    script: bld-pyqt-sip.bat  # [win]
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ stdlib('c') }}
      host:
        - python
        - setuptools
        - wheel
        - pip
      run:
        - python
    test:
      imports:
        - PyQt5.sip
      requires:
        - pip
      commands:
        - pip check

  - name: pyqt
    version: {{ version }}
    script: build-pyqt.sh  # [not win]
    script: bld-pyqt.bat  # [win]
    build:
      entry_points:
        - pyuic5 = PyQt5.uic.pyuic:main
      run_exports:
        - {{ pin_subpackage('pyqt', max_pin='x.x') }}
      missing_dso_whitelist:
        - $RPATH/libm.so.6
        - $RPATH/libpthread.so.0
        - $RPATH/libc.so.6
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - jom                                # [win]
        - make  # [not win]
        - pkg-config
      host:
        - python
        - pyqt-builder >=1.14.1,<2
        - sip {{ sip_version }}
        - qt-main 5.15.*
        - libgl-devel {{ libgl }}                # [linux]
        - libegl-devel {{ libegl }}              # [linux]
        - libopengl-devel {{ libopengl }}        # [linux]
        - xorg-xorgproto {{ xorg_xorgproto }}    # [linux]
        - xcb-util {{ xcb_util }}                # [linux]
        - xcb-util-wm {{ xcb_util_wm }}          # [linux]
        - xcb-util-keysyms {{ xcb_util_keysyms }}       # [linux]
        - xcb-util-image {{ xcb_util_image }}           # [linux]
        - xcb-util-renderutil {{ xcb_util_renderutil }} # [linux]
        - xorg-libx11 {{ xorg_libx11 }}                 # [linux]
        - xorg-libxext {{ xorg_libxext }}               # [linux]
        - xorg-libxdamage {{ xorg_libxdamage }}         # [linux]
        - xorg-libsm {{ xorg_libsm }}                   # [linux]
        - xorg-libice {{ xorg_libice }}                 # [linux]
        - xorg-libxcomposite {{ xorg_libxcomposite }}   # [linux]
        - xorg-libxxf86vm {{ xorg_libxxf86vm }}         # [linux]
        #- xorg-xf86vidmodeproto {{ xorg_xf86vidmodeproto }} # [linux]
      run:
        - qt-main 5.15*
        - python
        - {{ pin_subpackage('pyqt5-sip', exact=True) }}
    test:
      files:
        - pyqt_test.py
      imports:
        - PyQt5
        - PyQt5.sip
        - PyQt5.QtCore
        - PyQt5.QtGui
        - PyQt5.QtHelp
        - PyQt5.QtMultimedia
        - PyQt5.QtMultimediaWidgets
        - PyQt5.QtNetwork
        - PyQt5.QtOpenGL
        - PyQt5.QtPrintSupport
        - PyQt5.QtQml
        - PyQt5.QtQuick
        - PyQt5.QtSvg
        - PyQt5.QtTest
        - PyQt5.QtWebChannel
        - PyQt5.QtWebSockets
        - PyQt5.QtWidgets
        - PyQt5.QtXml
        - PyQt5.QtXmlPatterns
      requires:
        - pip
      commands:
        # we don't have xvfb on our builders ... so we might ignore it ..
        - DISPLAY=localhost:1.0 xvfb-run -a bash -c 'python pyqt_test.py' || true # [linux]
        - pyuic5 --version  # [not win]
        - pip check

  - name: pyqtwebengine
    version: {{ version }}
    script: build-pyqtwebengine.sh  # [not win]
    script: bld-pyqtwebengine.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('pyqtwebengine', max_pin='x.x') }}
      missing_dso_whitelist:
        - $RPATH/libm.so.6
        - $RPATH/libpthread.so.0
        - $RPATH/libc.so.6
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - jom                                    # [win]
        - make  # [not win]
        - pkg-config
      host:
        - python
        - pyqt-builder >=1.9,<2
        - sip {{ sip_version }}
        - {{ pin_subpackage('pyqt', exact=True) }}
        - qt-main 5.15.*
        - qt-webengine  5.15.*
        - libgl-devel {{ libgl }}                # [linux]
        - libegl-devel {{ libegl }}              # [linux]
        - libopengl-devel {{ libopengl }}        # [linux]
        - xorg-xorgproto {{ xorg_xorgproto }}    # [linux]
        - xcb-util {{ xcb_util }}                # [linux]
        - xcb-util-wm {{ xcb_util_wm }}          # [linux]
        - xcb-util-keysyms {{ xcb_util_keysyms }}       # [linux]
        - xcb-util-image {{ xcb_util_image }}           # [linux]
        - xcb-util-renderutil {{ xcb_util_renderutil }} # [linux]
        - xorg-libx11 {{ xorg_libx11 }}                 # [linux]
        - xorg-libxext {{ xorg_libxext }}               # [linux]
        - xorg-libxdamage {{ xorg_libxdamage }}         # [linux]
        - xorg-libsm {{ xorg_libsm }}                   # [linux]
        - xorg-libice {{ xorg_libice }}                 # [linux]
        - xorg-libxcomposite {{ xorg_libxcomposite }}   # [linux]
        - xorg-libxxf86vm {{ xorg_libxxf86vm }}         # [linux]
        # needed by qt-webengine at runtime - qt-webengine was built with cdts
        - xorg-libxrender {{ xorg_libxrender }}        # [linux]
        - xorg-libxrandr {{ xorg_libxrandr }}          # [linux]
        - xorg-libxtst {{ xorg_libxtst }}              # [linux]
        - xorg-libxfixes {{ xorg_libxfixes }}          # [linux]
        #- xorg-xf86vidmodeproto {{ xorg_xf86vidmodeproto }} # [linux]
      run:
        - qt-main 5.15.*
        - qt-webengine 5.15.*
        - python
        - {{ pin_subpackage('pyqt', max_pin='x.x') }}
    test:
      imports:
        - PyQt5.QtWebEngine
        - PyQt5.QtWebEngineCore
        - PyQt5.QtWebEngineWidgets
      requires:
        - pip
      commands:
        - pip check

  - name: pyqtchart
    version: {{ version }}
    script: build-pyqtcharts.sh  # [not win]
    script: bld-pyqtcharts.bat  # [win]
    build:
      run_exports:
        - {{ pin_subpackage('pyqtchart', max_pin='x.x') }}
      missing_dso_whitelist:
        - $RPATH/libm.so.6
        - $RPATH/libpthread.so.0
        - $RPATH/libc.so.6
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        - {{ stdlib('c') }}
        - jom                                    # [win]
        - make  # [not win]
        - pkg-config
      host:
        - python
        - pyqt-builder >=1.9,<2
        - sip {{ sip_version }}
        - qt-main 5.15.*
        - {{ pin_subpackage('pyqt', exact=True) }}
        - libgl-devel {{ libgl }}                # [linux]
        - libegl-devel {{ libegl }}              # [linux]
        - libopengl-devel {{ libopengl }}        # [linux]
        - xorg-xorgproto {{ xorg_xorgproto }}    # [linux]
        - xcb-util {{ xcb_util }}                # [linux]
        - xcb-util-wm {{ xcb_util_wm }}          # [linux]
        - xcb-util-keysyms {{ xcb_util_keysyms }}       # [linux]
        - xcb-util-image {{ xcb_util_image }}           # [linux]
        - xcb-util-renderutil {{ xcb_util_renderutil }} # [linux]
        - xorg-libx11 {{ xorg_libx11 }}                 # [linux]
        - xorg-libxext {{ xorg_libxext }}               # [linux]
        - xorg-libxdamage {{ xorg_libxdamage }}         # [linux]
        - xorg-libsm {{ xorg_libsm }}                   # [linux]
        - xorg-libice {{ xorg_libice }}                 # [linux]
        - xorg-libxcomposite {{ xorg_libxcomposite }}   # [linux]
        - xorg-libxxf86vm {{ xorg_libxxf86vm }}         # [linux]
        #- xorg-xf86vidmodeproto {{ xorg_xf86vidmodeproto }} # [linux]
      run:
        - qt-main 5.15.*
        - python
        - {{ pin_subpackage('pyqt', max_pin='x.x') }}
    test:
      imports:
        - PyQt5.QtChart
      requires:
        - pip
      commands:
        - pip check

about:
  home: https://www.riverbankcomputing.com/software/pyqt/
  license: GPL-3.0-only
  license_family: GPL
  license_file: pyqt/LICENSE
  summary: Python bindings for the Qt cross platform application toolkit
  description: |
    PyQt5 is a comprehensive set of Python bindings for Qt v5.
    It is implemented as more than 35 extension modules and enables Python
    to be used as an alternative application development language to C++ on
    all supported platforms including iOS and Android.
  doc_url: https://www.riverbankcomputing.com/static/Docs/PyQt5/
  dev_url: https://www.riverbankcomputing.com/mailman/listinfo/pyqt/

extra:
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - katietz
    - mingwandroid
    - gillins
    - msarahan
    - ocefpaf
    - jschueller
  feedstock-name: pyqt
