travis:
  secure:
    BINSTAR_TOKEN: kMPW2UAFmopcuB3t9UwbUo+wJ67YtzJAyoIXdm1AncY0N/03cn44YALrRJrrDx3TGv485+URbGyQcJq0be5f5jKmfDLHDin00jcuR+x2J/1EHtlhiJnydZHxqyPiXfUg/Fwb8arAXGSz2n3NOHB+zOsXI3A03Yhl/aIRL2Gb1Gj2DzB/flVeZqV1hNzPFHJqKNtIyprgw70lHXAVZ8h4ZJIs+U9jRYmh8ycn0CAInhUz6R+1yBGW9ZYJebnIF02zR2N2gHTzYg2Y3z50XfdRL6gllU6VSVH3EZg/c3mW1D13OXBUM4CpbZ/s8eYAYc8XoDUok60Jzot2A4v7bzQ2UCRhIB3Sio3hf4BNSDsvAlPpuH/erg9i8SXO64ZE/oX4RFoVraoSYmMRN9Dw2hXZDMeenDwqUVU74WMa9aiMBvnGBmLf4j+3nibwlShIniEMs+Al4a5ofZQXUFca4YFJlIGR1lw6XDJvcg6nJgqXylFq0JuMeGi/IGo/c2bQqFtFfTerxwcZhiZ8C7a7v/y/F3Ef5kPlFAXEgp8H6UzyHFLO3/arjIWcTlkOy3tyA5XHWtLBOYUuP4t4NhNTxVcViBc+qTss2KSjopIkwOhqBE8R6t1HRvsN+xZB4Gw6r3pwrjmECCTonVnjnGJPTLKFRWrwRfkizHv0jT4ysB0Ckoo=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
